### ISSUE TITLE
Assembly not included 

### ISSUE THREAD

**Issue by Pumpin** [skybrud/Skybrud.Umbraco.IconPicker#1]
Hey Rene u are using "Skybrud.WebApi.Json"assembly but it is not in the package could u remove the ref or update the package

**Comment by hfloyd** [comment]
I am seeing the same issue. Getting an error on package install.

![icon-picker-error](https://cloud.githubusercontent.com/assets/1252593/17038363/6b29209c-4f63-11e6-80fe-4ed164784e68.png)

**Comment by rpjengaard** [comment]
Hi Guys,

sorry for the inconvenience. I´m on holiday right now, but i managed to make an update on our. Try using v 1.0.0.3. I will release on NuGet and Github later. Let me know if there is still problems.

https://our.umbraco.org/FileDownload?id=16524

/R

**Comment by hfloyd** [comment]
Thank you, @rpjengaard !
Installed without issue :+1:
