### ISSUE TITLE
`:hover` style overrides Umbraco default

### ISSUE THREAD

**Issue by greystate** [skybrud/Skybrud.Umbraco.IconPicker#2]
The rule for hovered icons also affects the standard icon picker for a Document Type's icon...

https://github.com/skybrud/Skybrud.Umbraco.IconPicker/blob/4d737cde42542c9a8f113f22dbdb4cb193008f62/src/Skybrud.Umbraco.IconPicker/App_Plugins/Skybrud.Umbraco.IconPicker/styles/iconPicker.less#L30-L32

(Looks like it's kind of necessary though... ?)

**Comment by abjerner** [comment]
@greystate oh well ... as this has mostly been an internal package, we haven't been good at checking the issues. So sorry for the lack of reply.

I pushed a new release yesterday for which the UI has been rewritten a bit. So this should no longer be the case 😉
